# SPDX-FileCopyrightText: 2023 Eduardo Javier Alvarado Aarón <eduardo.javier.alvarado.aaron@gmail.com>
#
# SPDX-License-Identifier: Unlicense

liberapay: ejaa3
custom: https://www.paypal.com/donate/?hosted_button_id=YQ7KH78M54DMW
